-- Somente homologação vazia yqqrfgbvoexricjdxpis. Nunca aplicar em produção.
-- Estrutura capturada: duas tabelas legadas; zero linhas copiadas ou clínicas atribuídas.
-- Transformação explícita: privilégios de clientes removidos, FORCE RLS e veto restritivo.
-- Isto não estabelece um baseline completo de produção.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '60s';
set local search_path = pg_catalog, public, auth;
lock table auth.users, public.organizations in share mode;
do $empty_staging_guard$ begin
  if to_regclass('public.documentos') is not null or to_regclass('public.pacientes') is not null then
    raise exception 'Reconstrução exige as duas tabelas legadas ausentes';
  end if;
  if to_regprocedure('public.set_updated_at()') is not null then
    raise exception 'Reconstrução não substitui função pública preexistente';
  end if;
  if exists (select 1 from auth.users) or exists (select 1 from public.organizations)
     or exists (select 1 from public.patients) or exists (select 1 from public.encounters) then
    raise exception 'Reconstrução exige homologação vazia antes das fixtures';
  end if;
end $empty_staging_guard$;
create table "public"."documentos" (
  "id" bigint generated by default as identity (sequence name "public"."documentos_id_seq" start with 1 increment by 1 minvalue 1 maxvalue 9223372036854775807 cache 1 no cycle) not null,
  "user_id" uuid not null,
  "modulo" text collate "pg_catalog"."default" not null,
  "doc_id" text collate "pg_catalog"."default" not null,
  "dados" jsonb default '{}'::jsonb not null,
  "atualizado_em" timestamp with time zone default now() not null
);
alter table "public"."documentos" owner to "postgres";
alter table "public"."documentos" alter column "id" set storage plain;
alter table "public"."documentos" alter column "user_id" set storage plain;
alter table "public"."documentos" alter column "modulo" set storage extended;
alter table "public"."documentos" alter column "doc_id" set storage extended;
alter table "public"."documentos" alter column "dados" set storage extended;
alter table "public"."documentos" alter column "atualizado_em" set storage plain;
alter table "public"."documentos" add constraint "documentos_pkey" PRIMARY KEY (id);
alter table "public"."documentos" add constraint "documentos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table "public"."documentos" add constraint "documentos_user_id_modulo_doc_id_key" UNIQUE (user_id, modulo, doc_id);
CREATE INDEX documentos_user_idx ON public.documentos USING btree (user_id, modulo);
create policy "documentos_delete_proprio" on "public"."documentos" as permissive for delete to "authenticated" using ((auth.uid() = user_id));
create policy "documentos_insert_proprio" on "public"."documentos" as permissive for insert to "authenticated" with check ((auth.uid() = user_id));
create policy "documentos_select_proprio" on "public"."documentos" as permissive for select to "authenticated" using ((auth.uid() = user_id));
create policy "documentos_update_proprio" on "public"."documentos" as permissive for update to "authenticated" using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
alter table "public"."documentos" enable row level security;
alter table "public"."documentos" force row level security;
create policy "staging_legacy_channel_frozen" on "public"."documentos" as restrictive for all to "anon", "authenticated" using (false) with check (false);
revoke all on table "public"."documentos" from public, anon, authenticated;
revoke all ("id", "user_id", "modulo", "doc_id", "dados", "atualizado_em") on table "public"."documentos" from public, anon, authenticated;
grant delete on table "public"."documentos" to "service_role";
grant insert on table "public"."documentos" to "service_role";
grant maintain on table "public"."documentos" to "service_role";
grant references on table "public"."documentos" to "service_role";
grant select on table "public"."documentos" to "service_role";
grant trigger on table "public"."documentos" to "service_role";
grant truncate on table "public"."documentos" to "service_role";
grant update on table "public"."documentos" to "service_role";
revoke all on sequence "public"."documentos_id_seq" from public, anon, authenticated;
grant all on sequence "public"."documentos_id_seq" to "service_role";
create table "public"."pacientes" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid default auth.uid() not null,
  "nome" text collate "pg_catalog"."default" not null,
  "cpf" text collate "pg_catalog"."default",
  "data_nascimento" date,
  "telefone" text collate "pg_catalog"."default",
  "email" text collate "pg_catalog"."default",
  "convenio" text collate "pg_catalog"."default",
  "numero_carteirinha" text collate "pg_catalog"."default",
  "alergias" text collate "pg_catalog"."default",
  "comorbidades" text collate "pg_catalog"."default",
  "medicamentos_uso" text collate "pg_catalog"."default",
  "observacoes" text collate "pg_catalog"."default",
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);
alter table "public"."pacientes" owner to "postgres";
alter table "public"."pacientes" alter column "id" set storage plain;
alter table "public"."pacientes" alter column "user_id" set storage plain;
alter table "public"."pacientes" alter column "nome" set storage extended;
alter table "public"."pacientes" alter column "cpf" set storage extended;
alter table "public"."pacientes" alter column "data_nascimento" set storage plain;
alter table "public"."pacientes" alter column "telefone" set storage extended;
alter table "public"."pacientes" alter column "email" set storage extended;
alter table "public"."pacientes" alter column "convenio" set storage extended;
alter table "public"."pacientes" alter column "numero_carteirinha" set storage extended;
alter table "public"."pacientes" alter column "alergias" set storage extended;
alter table "public"."pacientes" alter column "comorbidades" set storage extended;
alter table "public"."pacientes" alter column "medicamentos_uso" set storage extended;
alter table "public"."pacientes" alter column "observacoes" set storage extended;
alter table "public"."pacientes" alter column "created_at" set storage plain;
alter table "public"."pacientes" alter column "updated_at" set storage plain;
alter table "public"."pacientes" add constraint "pacientes_pkey" PRIMARY KEY (id);
alter table "public"."pacientes" add constraint "pacientes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX pacientes_nome_idx ON public.pacientes USING btree (nome);
CREATE INDEX pacientes_user_id_idx ON public.pacientes USING btree (user_id);
CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;
alter function "public"."set_updated_at"() owner to "postgres";
revoke all on function "public"."set_updated_at"() from public, anon, authenticated;
grant execute on function "public"."set_updated_at"() to "service_role";
CREATE TRIGGER set_pacientes_updated_at BEFORE UPDATE ON public.pacientes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
create policy "Usuário atualiza apenas seus pacientes" on "public"."pacientes" as permissive for update to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Usuário cria apenas seus pacientes" on "public"."pacientes" as permissive for insert to public with check ((auth.uid() = user_id));
create policy "Usuário exclui apenas seus pacientes" on "public"."pacientes" as permissive for delete to public using ((auth.uid() = user_id));
create policy "Usuário vê apenas seus pacientes" on "public"."pacientes" as permissive for select to public using ((auth.uid() = user_id));
alter table "public"."pacientes" enable row level security;
alter table "public"."pacientes" force row level security;
create policy "staging_legacy_channel_frozen" on "public"."pacientes" as restrictive for all to "anon", "authenticated" using (false) with check (false);
revoke all on table "public"."pacientes" from public, anon, authenticated;
revoke all ("id", "user_id", "nome", "cpf", "data_nascimento", "telefone", "email", "convenio", "numero_carteirinha", "alergias", "comorbidades", "medicamentos_uso", "observacoes", "created_at", "updated_at") on table "public"."pacientes" from public, anon, authenticated;
grant delete on table "public"."pacientes" to "service_role";
grant insert on table "public"."pacientes" to "service_role";
grant maintain on table "public"."pacientes" to "service_role";
grant references on table "public"."pacientes" to "service_role";
grant select on table "public"."pacientes" to "service_role";
grant trigger on table "public"."pacientes" to "service_role";
grant truncate on table "public"."pacientes" to "service_role";
grant update on table "public"."pacientes" to "service_role";
notify pgrst, 'reload schema';
commit;
